apiVersion: v1
kind: Service
metadata:
  name: fast-api
spec:
  selector:
    app: fast-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 #incoming traffic in 80 is forwarded to port 80